_BASE_: "Base-PolyRCNN.yaml"
DATALOADER:
  NUM_WORKERS: 12
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("aicrowd_train",)
  TEST: ("aicrowd_test",)
SOLVER:
  STEPS: (947484, 1754600)  # 54th epoch
  MAX_ITER: 1754601  # 100th epoch
  CHECKPOINT_PERIOD: 17546  # save checkpoint per epoch
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 10000000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
